spring:
  application:
    name: core-app

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:master}
  client-id: ${KEYCLOAK_CLIENT_ID:client-id}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:client-secret}

